import type { UserRole } from "@/generated/prisma/enums";

export type Scope = "global" | "location" | "owner";

export interface LandingCard {
  href: string;
  title: string;
  description: string;
  tag: string;
  tagColor: string;
}

export interface RoleDefinition {
  label: string;
  description: string;
  normalizesTo: UserRole;
  visibleInPicker: boolean;
  suites: string[];
  allowedRoutes: string[];
  landingCards: LandingCard[];
  scope: Scope;
  badge: { color: string; abbrev: string };
  defaultCapabilities: {
    canScheduleSurveys: boolean;
    canScheduleInstalls: boolean;
    canScheduleInspections: boolean;
    canSyncZuper: boolean;
    canManageUsers: boolean;
    canManageAvailability: boolean;
    canEditDesign: boolean;
    canEditPermitting: boolean;
    canViewAllLocations: boolean;
  };
}

// Canonical role access definitions. Legacy roles mirror their canonical
// target so behaviour is identical if a legacy value escapes normalization.
// Data ported from:
//  - src/app/admin/users/page.tsx (labels, descriptions, badge colors)
//  - src/app/admin/directory/page.tsx (badge abbreviations, alt colors)
//  - src/lib/suite-nav.ts (suites)
//  - src/lib/role-permissions.ts (allowedRoutes, capability booleans)
//  - src/lib/access-scope.ts (scope)
//  - src/app/page.tsx (landing cards)

// ADMIN_ONLY routes are stripped from every canonical role below — they're
// dead entries per ROLE_PERMISSIONS (short-circuited by canAccessRoute).
// Kept here as documentation of the sentinel list:
// ["/admin", "/api/admin", "/dashboards/zuper-status-comparison",
//  "/dashboards/product-comparison", "/dashboards/mobile", "/dashboards/inventory",
//  "/dashboards/catalog", "/dashboards/command-center", "/dashboards/capacity",
//  "/dashboards/locations", "/api/chat"]

const ADMIN: RoleDefinition = {
  label: "Admin",
  description: "Full access, can manage users",
  normalizesTo: "ADMIN",
  visibleInPicker: true,
  suites: [
    "/suites/operations",
    "/suites/design-engineering",
    "/suites/permitting-interconnection",
    "/suites/intelligence",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/executive",
    "/suites/accounting",
  ],
  allowedRoutes: ["*"],
  landingCards: [],
  scope: "global",
  badge: { color: "red", abbrev: "ADMIN" },
  defaultCapabilities: {
    canScheduleSurveys: true,
    canScheduleInstalls: true,
    canScheduleInspections: true,
    canSyncZuper: true,
    canManageUsers: true,
    canManageAvailability: true,
    canEditDesign: true,
    canEditPermitting: true,
    canViewAllLocations: true,
  },
};

const EXECUTIVE: RoleDefinition = {
  label: "Executive",
  description: "Executive access like Admin, but cannot manage users",
  normalizesTo: "EXECUTIVE",
  visibleInPicker: true,
  suites: [
    "/suites/operations",
    "/suites/design-engineering",
    "/suites/permitting-interconnection",
    "/suites/intelligence",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/executive",
    "/suites/accounting",
  ],
  allowedRoutes: ["*"],
  landingCards: [],
  scope: "global",
  badge: { color: "amber", abbrev: "EXECUTIVE" },
  defaultCapabilities: {
    canScheduleSurveys: true,
    canScheduleInstalls: true,
    canScheduleInspections: true,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: true,
    canEditDesign: true,
    canEditPermitting: true,
    canViewAllLocations: true,
  },
};

const OPERATIONS_MANAGER: RoleDefinition = {
  label: "Operations Manager",
  description: "Crew oversight, scheduling, availability management",
  normalizesTo: "OPERATIONS_MANAGER",
  visibleInPicker: true,
  suites: [
    "/suites/operations",
    "/suites/intelligence",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/accounting",
  ],
  allowedRoutes: [
    "/",
    "/suites/operations",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/intelligence",
    "/suites/accounting",
    "/dashboards/scheduler",
    "/dashboards/forecast-schedule",
    "/dashboards/site-survey-scheduler",
    "/dashboards/site-survey",
    "/dashboards/construction-scheduler",
    "/dashboards/construction",
    "/dashboards/inspection-scheduler",
    "/dashboards/service-scheduler",
    "/dashboards/dnr-scheduler",
    "/dashboards/equipment-backlog",
    "/dashboards/service-backlog",
    "/dashboards/service",
    "/dashboards/service-overview",
    "/dashboards/service-tickets",
    "/dashboards/service-catalog",
    "/dashboards/service-customers",
    "/dashboards/timeline",
    "/dashboards/bom",
    "/dashboards/bom/history",
    "/dashboards/pricing-calculator",
    "/dashboards/pe-deals",
    "/api/accounting",
    "/dashboards/ai",
    "/dashboards/dnr",
    "/dashboards/roofing",
    "/dashboards/roofing-scheduler",
    "/dashboards/construction-metrics",
    "/dashboards/inspection-metrics",
    "/dashboards/survey-metrics",
    "/api/hubspot/qc-metrics",
    "/dashboards/at-risk",
    "/dashboards/qc",
    "/dashboards/alerts",
    "/dashboards/pipeline",
    "/dashboards/optimizer",
    "/dashboards/pe",
    "/dashboards/sales",
    "/dashboards/project-management",
    "/dashboards/design-engineering",
    "/dashboards/permitting-interconnection",
    "/suites/executive",
    "/dashboards/executive",
    "/dashboards/executive-calendar",
    "/dashboards/revenue",
    "/dashboards/forecast-accuracy",
    "/dashboards/forecast-timeline",
    "/dashboards/preconstruction-metrics",
    "/dashboards/zuper-compliance",
    "/dashboards/design-pipeline-funnel",
    "/dashboards/territory-map",
    "/api/territory-map",
    "/api/forecasting",
    "/dashboards/office-performance",
    "/api/office-performance",
    "/dashboards/product-catalog",
    "/dashboards/submit-product",
    "/dashboards/solar-designer",
    "/api/solar-designer",
    "/api/projects",
    "/api/bom",
    "/api/catalog",
    "/api/products",
    "/api/service",
    "/api/zuper",
    "/api/activity/log",
    "/api/inventory",
    "/api/bugs",
    "/dashboards/deals",
    "/api/deals",
    "/dashboards/reviews",
    "/api/reviews",
    "/dashboards/inspections",
    "/api/install-review",
    "/api/solar",
    "/sop",
    "/api/sop",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
    // On-Call Electrician Rotations (viewing). Approval paths gated at handler level.
    "/dashboards/on-call",
    "/api/on-call",
  ],
  landingCards: [
    { href: "/dashboards/scheduler", title: "Master Schedule", description: "Drag-and-drop scheduling calendar with crew management.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/construction-scheduler", title: "Construction Schedule", description: "Construction installs with Zuper integration.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/equipment-backlog", title: "Equipment Backlog", description: "Equipment forecasting by brand, model, and stage.", tag: "EQUIPMENT", tagColor: "blue" },
    { href: "/dashboards/timeline", title: "Timeline View", description: "Gantt-style project progression and milestones.", tag: "PLANNING", tagColor: "blue" },
    { href: "/dashboards/at-risk", title: "At-Risk Projects", description: "Overdue milestones, stalled stages, severity scoring.", tag: "AT-RISK", tagColor: "orange" },
    { href: "/dashboards/qc", title: "QC Metrics", description: "Time-between-stages analytics.", tag: "QC", tagColor: "cyan" },
  ],
  scope: "global",
  badge: { color: "amber", abbrev: "OPS MGR" },
  defaultCapabilities: {
    canScheduleSurveys: true,
    canScheduleInstalls: true,
    canScheduleInspections: true,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: true,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: true,
  },
};

const PROJECT_MANAGER: RoleDefinition = {
  label: "Project Manager",
  description: "Can access Operations, D&E, P&I, and Intelligence Suites",
  normalizesTo: "PROJECT_MANAGER",
  visibleInPicker: true,
  suites: [
    "/suites/operations",
    "/suites/design-engineering",
    "/suites/permitting-interconnection",
    "/suites/intelligence",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/accounting",
  ],
  allowedRoutes: [
    "/",
    "/suites/operations",
    "/suites/design-engineering",
    "/suites/permitting-interconnection",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/intelligence",
    "/suites/executive",
    "/suites/accounting",
    "/dashboards/scheduler",
    "/dashboards/forecast-schedule",
    "/dashboards/site-survey-scheduler",
    "/dashboards/construction-scheduler",
    "/dashboards/inspection-scheduler",
    "/dashboards/service-scheduler",
    "/dashboards/dnr-scheduler",
    "/dashboards/equipment-backlog",
    "/dashboards/service-backlog",
    "/dashboards/service",
    "/dashboards/service-overview",
    "/dashboards/service-tickets",
    "/dashboards/service-catalog",
    "/dashboards/service-customers",
    "/dashboards/timeline",
    "/dashboards/bom",
    "/dashboards/bom/history",
    "/dashboards/pricing-calculator",
    "/dashboards/pe-deals",
    "/api/accounting",
    "/dashboards/ai",
    "/dashboards/dnr",
    "/dashboards/roofing",
    "/dashboards/roofing-scheduler",
    "/dashboards/site-survey",
    "/dashboards/design",
    "/dashboards/permitting",
    "/dashboards/inspections",
    "/dashboards/interconnection",
    "/dashboards/construction",
    "/dashboards/construction-metrics",
    "/dashboards/inspection-metrics",
    "/dashboards/survey-metrics",
    "/dashboards/incentives",
    "/api/hubspot/qc-metrics",
    "/dashboards/at-risk",
    "/dashboards/qc",
    "/dashboards/alerts",
    "/dashboards/pipeline",
    "/dashboards/optimizer",
    "/dashboards/pe",
    "/dashboards/sales",
    "/dashboards/project-management",
    "/dashboards/design-engineering",
    "/dashboards/permitting-interconnection",
    "/dashboards/executive",
    "/dashboards/executive-calendar",
    "/dashboards/revenue",
    "/dashboards/forecast-accuracy",
    "/dashboards/forecast-timeline",
    "/dashboards/preconstruction-metrics",
    "/dashboards/design-pipeline-funnel",
    "/dashboards/territory-map",
    "/api/territory-map",
    "/api/forecasting",
    "/dashboards/office-performance",
    "/api/office-performance",
    "/dashboards/de-overview",
    "/dashboards/plan-review",
    "/dashboards/pending-approval",
    "/dashboards/design-revisions",
    "/dashboards/de-metrics",
    "/api/hubspot/da-rework-flags",
    "/dashboards/clipping-analytics",
    "/dashboards/ahj-requirements",
    "/dashboards/utility-design-requirements",
    "/dashboards/solar-surveyor",
    "/dashboards/solar-designer",
    "/api/solar-designer",
    "/dashboards/pi-overview",
    "/dashboards/pi-metrics",
    "/dashboards/pi-action-queue",
    "/dashboards/pi-revisions",
    "/dashboards/pi-permit-action-queue",
    "/dashboards/pi-ic-action-queue",
    "/dashboards/pi-permit-revisions",
    "/dashboards/pi-ic-revisions",
    "/dashboards/ahj-tracker",
    "/dashboards/utility-tracker",
    "/dashboards/pi-timeline",
    "/dashboards/product-catalog",
    "/dashboards/submit-product",
    "/api/projects",
    "/api/bom",
    "/api/catalog",
    "/api/products",
    "/api/service",
    "/api/zuper",
    "/api/activity/log",
    "/api/inventory",
    "/api/bugs",
    "/api/ahj",
    "/api/utility",
    "/dashboards/deals",
    "/api/deals",
    "/dashboards/reviews",
    "/api/reviews",
    "/dashboards/inspections",
    "/api/install-review",
    "/api/solar",
    "/sop",
    "/api/sop",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
    // On-Call Electrician Rotations (viewing). Approval paths gated at handler level.
    "/dashboards/on-call",
    "/api/on-call",
  ],
  landingCards: [
    { href: "/dashboards/pipeline", title: "Pipeline Overview", description: "Full pipeline with filters and milestone tracking.", tag: "PIPELINE", tagColor: "green" },
    { href: "/dashboards/at-risk", title: "At-Risk Projects", description: "Overdue milestones, stalled stages, severity scoring.", tag: "AT-RISK", tagColor: "orange" },
    { href: "/dashboards/project-management", title: "Project Management", description: "PM workload, DA backlog, stuck deals.", tag: "PM", tagColor: "green" },
    { href: "/dashboards/timeline", title: "Timeline View", description: "Gantt-style project progression and milestones.", tag: "PLANNING", tagColor: "blue" },
    { href: "/dashboards/equipment-backlog", title: "Equipment Backlog", description: "Equipment forecasting by brand, model, and stage.", tag: "EQUIPMENT", tagColor: "blue" },
  ],
  scope: "global",
  badge: { color: "indigo", abbrev: "PM" },
  defaultCapabilities: {
    canScheduleSurveys: true,
    canScheduleInstalls: true,
    canScheduleInspections: true,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: false,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: true,
  },
};

const OPERATIONS: RoleDefinition = {
  label: "Operations",
  description: "Only access to Operations Suite",
  normalizesTo: "OPERATIONS",
  visibleInPicker: true,
  suites: [
    "/suites/operations",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/accounting",
  ],
  allowedRoutes: [
    "/",
    "/suites/operations",
    "/suites/service",
    "/suites/dnr-roofing",
    "/suites/accounting",
    "/dashboards/scheduler",
    "/dashboards/forecast-schedule",
    "/dashboards/site-survey-scheduler",
    "/dashboards/site-survey",
    "/dashboards/construction-scheduler",
    "/dashboards/construction",
    "/dashboards/inspection-scheduler",
    "/dashboards/service-scheduler",
    "/dashboards/dnr-scheduler",
    "/dashboards/equipment-backlog",
    "/dashboards/service-backlog",
    "/dashboards/service",
    "/dashboards/service-overview",
    "/dashboards/service-tickets",
    "/dashboards/service-catalog",
    "/dashboards/service-customers",
    "/dashboards/timeline",
    "/dashboards/bom",
    "/dashboards/bom/history",
    "/dashboards/pricing-calculator",
    "/dashboards/pe-deals",
    "/api/accounting",
    "/dashboards/dnr",
    "/dashboards/roofing",
    "/dashboards/roofing-scheduler",
    "/dashboards/construction-metrics",
    "/dashboards/inspection-metrics",
    "/dashboards/survey-metrics",
    "/api/hubspot/qc-metrics",
    "/dashboards/product-catalog",
    "/dashboards/submit-product",
    "/dashboards/solar-designer",
    "/api/solar-designer",
    "/api/projects",
    "/api/bom",
    "/api/catalog",
    "/api/products",
    "/api/service",
    "/api/zuper",
    "/api/activity/log",
    "/api/inventory",
    "/api/bugs",
    "/dashboards/deals",
    "/api/deals",
    "/dashboards/inspections",
    "/api/install-review",
    "/api/solar",
    "/sop",
    "/api/sop",
    "/api/forecasting",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
    // On-Call Electrician Rotations (viewing). Approval paths gated at handler level.
    "/dashboards/on-call",
    "/api/on-call",
  ],
  landingCards: [
    { href: "/dashboards/scheduler", title: "Master Schedule", description: "Drag-and-drop scheduling calendar with crew management.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/site-survey-scheduler", title: "Site Survey Schedule", description: "Site survey scheduling with Zuper integration.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/construction-scheduler", title: "Construction Schedule", description: "Construction installs with Zuper integration.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/inspection-scheduler", title: "Inspection Schedule", description: "Inspections with Zuper integration.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/equipment-backlog", title: "Equipment Backlog", description: "Equipment forecasting by brand, model, and stage.", tag: "EQUIPMENT", tagColor: "blue" },
    { href: "/dashboards/timeline", title: "Timeline View", description: "Gantt-style project progression and milestones.", tag: "PLANNING", tagColor: "blue" },
    { href: "/dashboards/comms", title: "Comms", description: "Unified inbox — Gmail, HubSpot, and Google Chat.", tag: "COMMS", tagColor: "cyan" },
  ],
  scope: "location",
  badge: { color: "orange", abbrev: "OPS" },
  defaultCapabilities: {
    canScheduleSurveys: false,
    canScheduleInstalls: true,
    canScheduleInspections: true,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: true,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: true,
  },
};

const SERVICE: RoleDefinition = {
  label: "Service",
  description: "Only access to Service Suite (tickets, priority queue, service scheduling)",
  normalizesTo: "SERVICE",
  visibleInPicker: true,
  suites: ["/suites/service"],
  allowedRoutes: [
    "/",
    "/suites/service",
    "/dashboards/service",
    "/dashboards/service-overview",
    "/dashboards/service-tickets",
    "/dashboards/service-customers",
    "/dashboards/service-backlog",
    "/dashboards/service-scheduler",
    "/dashboards/service-catalog",
    "/dashboards/deals",
    "/api/deals",
    "/api/projects",
    "/dashboards/equipment-backlog",
    "/dashboards/product-catalog",
    "/api/service",
    "/api/zuper",
    "/api/properties",
    "/api/catalog",
    "/api/products",
    "/api/inventory",
    "/api/hubspot/qc-metrics",
    "/api/activity/log",
    "/api/bugs",
    "/dashboards/solar-surveyor",
    "/api/solar",
    "/sop",
    "/api/sop",
    // On-Call Electrician Rotations (viewing only).
    "/dashboards/on-call",
    "/api/on-call",
    // My Tasks (personal HubSpot tasks view, available to every user)
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
  ],
  landingCards: [
    { href: "/dashboards/service-overview", title: "Service Overview", description: "Priority queue command center — see what needs attention now.", tag: "OVERVIEW", tagColor: "orange" },
    { href: "/dashboards/service-tickets", title: "Ticket Board", description: "Kanban board for HubSpot service tickets — filter, reassign, status, notes.", tag: "TICKETS", tagColor: "orange" },
    { href: "/dashboards/service-scheduler", title: "Service Schedule", description: "Calendar view of Zuper service visit and revisit jobs.", tag: "SCHEDULING", tagColor: "orange" },
  ],
  scope: "global",
  badge: { color: "teal", abbrev: "SERVICE" },
  defaultCapabilities: {
    canScheduleSurveys: false,
    canScheduleInstalls: false,
    canScheduleInspections: false,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: false,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: true,
  },
};

const TECH_OPS: RoleDefinition = {
  label: "Tech Ops",
  description: "Access to Operations, D&E, and P&I Suites",
  normalizesTo: "TECH_OPS",
  visibleInPicker: true,
  suites: [
    "/suites/operations",
    "/suites/design-engineering",
    "/suites/permitting-interconnection",
    "/suites/accounting",
  ],
  allowedRoutes: [
    "/",
    "/suites/design-engineering",
    "/suites/permitting-interconnection",
    "/suites/operations",
    "/suites/accounting",
    "/dashboards/site-survey",
    "/dashboards/design",
    "/dashboards/permitting",
    "/dashboards/inspections",
    "/dashboards/interconnection",
    "/dashboards/construction",
    "/dashboards/construction-metrics",
    "/dashboards/inspection-metrics",
    "/dashboards/survey-metrics",
    "/dashboards/incentives",
    "/api/hubspot/qc-metrics",
    "/dashboards/scheduler",
    "/dashboards/forecast-schedule",
    "/dashboards/site-survey-scheduler",
    "/dashboards/construction-scheduler",
    "/dashboards/inspection-scheduler",
    "/dashboards/service-scheduler",
    "/dashboards/dnr-scheduler",
    "/dashboards/equipment-backlog",
    "/dashboards/service-backlog",
    "/dashboards/service",
    "/dashboards/service-tickets",
    "/dashboards/service-catalog",
    "/dashboards/service-customers",
    "/dashboards/timeline",
    "/dashboards/bom",
    "/dashboards/bom/history",
    "/dashboards/pricing-calculator",
    "/dashboards/pe-deals",
    "/api/accounting",
    "/dashboards/dnr",
    "/dashboards/roofing",
    "/dashboards/roofing-scheduler",
    "/dashboards/de-overview",
    "/dashboards/plan-review",
    "/dashboards/pending-approval",
    "/dashboards/design-revisions",
    "/dashboards/de-metrics",
    "/api/hubspot/da-rework-flags",
    "/dashboards/clipping-analytics",
    "/dashboards/ahj-requirements",
    "/dashboards/utility-design-requirements",
    "/dashboards/solar-surveyor",
    "/dashboards/solar-designer",
    "/api/solar-designer",
    "/dashboards/pi-overview",
    "/dashboards/pi-metrics",
    "/dashboards/pi-action-queue",
    "/dashboards/pi-revisions",
    "/dashboards/pi-permit-action-queue",
    "/dashboards/pi-ic-action-queue",
    "/dashboards/pi-permit-revisions",
    "/dashboards/pi-ic-revisions",
    "/dashboards/ahj-tracker",
    "/dashboards/utility-tracker",
    "/dashboards/pi-timeline",
    "/dashboards/product-catalog",
    "/dashboards/submit-product",
    "/api/projects",
    "/api/bom",
    "/api/catalog",
    "/api/products",
    "/api/service",
    "/api/zuper",
    "/api/activity/log",
    "/api/inventory",
    "/api/bugs",
    "/api/ahj",
    "/api/utility",
    "/dashboards/deals",
    "/dashboards/design-pipeline-funnel",
    "/api/deals",
    "/dashboards/reviews",
    "/api/reviews",
    "/dashboards/inspections",
    "/api/install-review",
    "/api/solar",
    "/dashboards/ai",
    "/sop",
    "/api/sop",
    "/api/forecasting",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
    // On-Call Electrician Rotations (viewing). Approval paths gated at handler level.
    "/dashboards/on-call",
    "/api/on-call",
  ],
  landingCards: [
    { href: "/dashboards/site-survey", title: "Site Survey", description: "Site survey scheduling and status tracking.", tag: "SURVEY", tagColor: "green" },
    { href: "/dashboards/design", title: "Design & Engineering", description: "Design progress, engineering approvals, and plan sets.", tag: "DESIGN", tagColor: "green" },
    { href: "/dashboards/construction", title: "Construction", description: "Construction status, scheduling, and progress.", tag: "CONSTRUCTION", tagColor: "green" },
    { href: "/dashboards/inspections", title: "Inspections", description: "Inspection scheduling, pass rates, and AHJ analysis.", tag: "INSPECTIONS", tagColor: "green" },
  ],
  scope: "global",
  badge: { color: "yellow", abbrev: "TECH OPS" },
  defaultCapabilities: {
    canScheduleSurveys: false,
    canScheduleInstalls: false,
    canScheduleInspections: false,
    canSyncZuper: false,
    canManageUsers: false,
    canManageAvailability: true,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: false,
  },
};

const SALES_MANAGER: RoleDefinition = {
  label: "Sales Manager",
  description: "Sales team oversight — Accounting Suite access for pipeline visibility",
  normalizesTo: "SALES_MANAGER",
  visibleInPicker: true,
  suites: ["/suites/accounting"],
  allowedRoutes: [
    "/",
    "/suites/operations",
    "/suites/intelligence",
    "/suites/executive",
    "/suites/accounting",
    "/dashboards/sales",
    "/dashboards/deals",
    "/dashboards/pipeline",
    "/dashboards/site-survey-scheduler",
    "/dashboards/forecast-schedule",
    "/dashboards/forecast-timeline",
    "/dashboards/forecast-accuracy",
    "/dashboards/scheduler",
    "/dashboards/construction-scheduler",
    "/dashboards/inspection-scheduler",
    "/dashboards/timeline",
    "/dashboards/construction",
    "/dashboards/survey-metrics",
    "/dashboards/at-risk",
    "/dashboards/qc",
    "/dashboards/alerts",
    "/dashboards/optimizer",
    "/dashboards/pe",
    "/dashboards/pe-deals",
    "/api/accounting",
    "/dashboards/pricing-calculator",
    "/dashboards/project-management",
    "/dashboards/executive",
    "/dashboards/executive-calendar",
    "/dashboards/revenue",
    "/api/projects",
    "/api/deals",
    "/api/forecasting",
    "/api/revenue-goals",
    "/api/zuper/availability",
    "/api/zuper/status",
    "/api/zuper/jobs/lookup",
    "/api/zuper/jobs/schedule",
    "/api/activity/log",
    "/api/bugs",
    "/sop",
    "/api/sop",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
  ],
  landingCards: [],
  scope: "global",
  badge: { color: "cyan", abbrev: "SALES MGR" },
  defaultCapabilities: {
    canScheduleSurveys: true,
    canScheduleInstalls: false,
    canScheduleInspections: false,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: false,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: true,
  },
};

const SALES: RoleDefinition = {
  label: "Sales",
  description: "Only access to Site Survey Schedule",
  normalizesTo: "SALES",
  visibleInPicker: true,
  suites: [],
  allowedRoutes: [
    "/",
    "/dashboards/site-survey-scheduler",
    "/dashboards/sales",
    "/dashboards/deals",
    "/api/deals",
    "/api/projects",
    "/api/zuper/availability",
    "/api/zuper/status",
    "/api/zuper/jobs/lookup",
    "/api/zuper/jobs/schedule",
    "/api/zuper/my-availability",
    "/api/bugs",
    "/sop",
    "/api/sop",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
  ],
  landingCards: [
    { href: "/dashboards/sales", title: "Sales Pipeline", description: "Active deals, funnel visualization, and proposal tracking.", tag: "SALES", tagColor: "cyan" },
    { href: "/dashboards/site-survey-scheduler", title: "Site Survey Schedule", description: "Schedule site surveys with Zuper integration.", tag: "SCHEDULING", tagColor: "blue" },
    { href: "/dashboards/comms", title: "Comms", description: "Unified inbox — Gmail, HubSpot, and Google Chat.", tag: "COMMS", tagColor: "cyan" },
  ],
  scope: "owner",
  badge: { color: "cyan", abbrev: "SALES" },
  defaultCapabilities: {
    canScheduleSurveys: true,
    canScheduleInstalls: false,
    canScheduleInspections: false,
    canSyncZuper: true,
    canManageUsers: false,
    canManageAvailability: false,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: false,
  },
};

const VIEWER: RoleDefinition = {
  label: "Viewer",
  description: "Unassigned — no dashboard access until role is set",
  normalizesTo: "VIEWER",
  visibleInPicker: true,
  suites: [],
  allowedRoutes: [
    "/",
    "/unassigned",
    "/dashboards/deals",
    "/api/deals",
    "/api/projects",
    "/api/activity/log",
    "/api/user/me",
    "/api/solar",
    "/sop",
    "/api/sop",
    "/dashboards/idr-meeting",
    "/api/idr-meeting",
    "/dashboards/comms",
    "/dashboards/my-tasks",
    "/api/hubspot/tasks/mine",
    "/api/comms",
  ],
  landingCards: [],
  scope: "location",
  badge: { color: "zinc", abbrev: "UNASSIGNED" },
  defaultCapabilities: {
    canScheduleSurveys: false,
    canScheduleInstalls: false,
    canScheduleInspections: false,
    canSyncZuper: false,
    canManageUsers: false,
    canManageAvailability: false,
    canEditDesign: false,
    canEditPermitting: false,
    canViewAllLocations: true,
  },
};

// Legacy roles mirror the access fields of their canonical target so behaviour
// is identical if a legacy value escapes normalization. Identity fields
// (label, description, normalizesTo, visibleInPicker, badge) stay unique.

const OWNER: RoleDefinition = {
  label: "Owner",
  description: "Executive access like Admin, but cannot manage users",
  normalizesTo: "EXECUTIVE",
  visibleInPicker: false,
  suites: EXECUTIVE.suites,
  allowedRoutes: EXECUTIVE.allowedRoutes,
  landingCards: EXECUTIVE.landingCards,
  scope: EXECUTIVE.scope,
  badge: { color: "amber", abbrev: "EXECUTIVE" },
  defaultCapabilities: EXECUTIVE.defaultCapabilities,
};

const MANAGER: RoleDefinition = {
  label: "Manager",
  description: "Legacy role — normalized to Project Manager",
  normalizesTo: "PROJECT_MANAGER",
  visibleInPicker: false,
  suites: PROJECT_MANAGER.suites,
  allowedRoutes: PROJECT_MANAGER.allowedRoutes,
  landingCards: PROJECT_MANAGER.landingCards,
  scope: PROJECT_MANAGER.scope,
  badge: { color: "indigo", abbrev: "PM" },
  defaultCapabilities: PROJECT_MANAGER.defaultCapabilities,
};

const DESIGNER: RoleDefinition = {
  label: "Designer",
  description: "Legacy role — normalized to Tech Ops",
  normalizesTo: "TECH_OPS",
  visibleInPicker: false,
  suites: TECH_OPS.suites,
  allowedRoutes: TECH_OPS.allowedRoutes,
  landingCards: TECH_OPS.landingCards,
  scope: TECH_OPS.scope,
  badge: { color: "emerald", abbrev: "TECH OPS" },
  defaultCapabilities: TECH_OPS.defaultCapabilities,
};

const PERMITTING: RoleDefinition = {
  label: "Permitting",
  description: "Legacy role — normalized to Tech Ops",
  normalizesTo: "TECH_OPS",
  visibleInPicker: false,
  suites: TECH_OPS.suites,
  allowedRoutes: TECH_OPS.allowedRoutes,
  landingCards: TECH_OPS.landingCards,
  scope: TECH_OPS.scope,
  badge: { color: "emerald", abbrev: "TECH OPS" },
  defaultCapabilities: TECH_OPS.defaultCapabilities,
};

export const ROLES: Record<UserRole, RoleDefinition> = {
  ADMIN,
  EXECUTIVE,
  OWNER,
  MANAGER,
  OPERATIONS,
  OPERATIONS_MANAGER,
  SERVICE,
  PROJECT_MANAGER,
  SALES_MANAGER,
  TECH_OPS,
  DESIGNER,
  PERMITTING,
  VIEWER,
  SALES,
};

/**
 * Routes that require ADMIN role even if the role's allowedRoutes would otherwise
 * permit access. Non-admin roles can be granted exceptions via ADMIN_ONLY_EXCEPTIONS.
 */
export const ADMIN_ONLY_ROUTES: string[] = [
  "/admin",
  "/api/admin",
  "/dashboards/zuper-status-comparison",
  "/dashboards/product-comparison",
  "/dashboards/mobile",
  "/dashboards/inventory",
  "/dashboards/catalog",
  "/dashboards/command-center",
  "/dashboards/capacity",
  "/dashboards/locations",
  "/api/chat",
];

/**
 * Sub-routes exempt from the admin-only restriction above.
 * Accessible to any role that has the parent route in their allowedRoutes.
 */
export const ADMIN_ONLY_EXCEPTIONS: string[] = [
  "/dashboards/catalog/new",
  "/api/catalog/push-requests",
  "/api/catalog/extract-from-datasheet",
  "/api/catalog/upload-photo",
];
