export type InternalPrototypeGroup =
  | "operations"
  | "department"
  | "executive"
  | "service"
  | "additional_pipeline"
  | "admin_tools"
  | "admin_testing"
  | "documentation"
  | "legacy";

export interface InternalPagePrototype {
  slug: string;
  targetHref: string;
  title: string;
  description: string;
  group: InternalPrototypeGroup;
  tags: string[];
}

export const INTERNAL_GROUP_LABELS: Record<InternalPrototypeGroup, string> = {
  operations: "Operations Suite",
  department: "Department Suite",
  executive: "Executive Suite",
  service: "Service Suite",
  additional_pipeline: "Additional Pipeline Suite",
  admin_tools: "Admin Suite: Tools",
  admin_testing: "Admin Suite: Testing Dashboards",
  documentation: "Admin Suite: Documentation",
  legacy: "Admin Suite: Legacy Prototypes",
};

export const INTERNAL_GROUP_ORDER: InternalPrototypeGroup[] = [
  "operations",
  "department",
  "executive",
  "service",
  "additional_pipeline",
  "admin_tools",
  "admin_testing",
  "documentation",
  "legacy",
];

export const INTERNAL_PAGE_PROTOTYPES: InternalPagePrototype[] = [
  {
    slug: "scheduler",
    targetHref: "/dashboards/scheduler",
    title: "Master Schedule",
    description: "Drag-and-drop scheduling calendar with crew management.",
    group: "operations",
    tags: ["scheduling", "operations"],
  },
  {
    slug: "site-survey-scheduler",
    targetHref: "/dashboards/site-survey-scheduler",
    title: "Site Survey Schedule",
    description: "Dedicated calendar for scheduling site surveys with Zuper integration.",
    group: "operations",
    tags: ["scheduling", "operations"],
  },
  {
    slug: "construction-scheduler",
    targetHref: "/dashboards/construction-scheduler",
    title: "Construction Schedule",
    description: "Dedicated calendar for scheduling construction installs with Zuper integration.",
    group: "operations",
    tags: ["scheduling", "operations"],
  },
  {
    slug: "inspection-scheduler",
    targetHref: "/dashboards/inspection-scheduler",
    title: "Inspection Schedule",
    description: "Dedicated calendar for scheduling inspections with Zuper integration.",
    group: "operations",
    tags: ["scheduling", "operations"],
  },
  {
    slug: "dnr-scheduler",
    targetHref: "/dashboards/dnr-scheduler",
    title: "D&R Schedule",
    description: "Calendar view of Zuper detach, reset, and D&R inspection jobs.",
    group: "operations",
    tags: ["scheduling", "operations"],
  },
  {
    slug: "timeline",
    targetHref: "/dashboards/timeline",
    title: "Timeline View",
    description: "Gantt-style timeline showing project progression and milestones.",
    group: "operations",
    tags: ["planning", "operations"],
  },
  {
    slug: "equipment-backlog",
    targetHref: "/dashboards/equipment-backlog",
    title: "Equipment Backlog",
    description: "Equipment forecasting by brand, model, and stage with location filtering.",
    group: "operations",
    tags: ["equipment", "operations"],
  },
  {
    slug: "inventory",
    targetHref: "/dashboards/inventory",
    title: "Inventory Hub",
    description: "Warehouse stock levels, receiving, and demand vs. supply gap analysis.",
    group: "operations",
    tags: ["inventory", "operations", "admin"],
  },
  {
    slug: "site-survey",
    targetHref: "/dashboards/site-survey",
    title: "Site Survey",
    description: "Site survey scheduling, status tracking, and completion monitoring.",
    group: "department",
    tags: ["survey", "department"],
  },
  {
    slug: "design",
    targetHref: "/dashboards/design",
    title: "Design & Engineering",
    description: "Track design progress, engineering approvals, and plan sets.",
    group: "department",
    tags: ["design", "department"],
  },
  {
    slug: "permitting",
    targetHref: "/dashboards/permitting",
    title: "Permitting",
    description: "Permit status tracking, submission dates, and approval monitoring.",
    group: "department",
    tags: ["permitting", "department"],
  },
  {
    slug: "inspections",
    targetHref: "/dashboards/inspections",
    title: "Inspections",
    description: "Inspection scheduling, status tracking, pass rates, and AHJ analysis.",
    group: "department",
    tags: ["inspection", "department"],
  },
  {
    slug: "interconnection",
    targetHref: "/dashboards/interconnection",
    title: "Interconnection",
    description: "Utility interconnection applications, approvals, and meter installations.",
    group: "department",
    tags: ["utility", "department"],
  },
  {
    slug: "construction",
    targetHref: "/dashboards/construction",
    title: "Construction",
    description: "Construction status, scheduling, and progress tracking.",
    group: "department",
    tags: ["construction", "department"],
  },
  {
    slug: "incentives",
    targetHref: "/dashboards/incentives",
    title: "Incentives",
    description: "Rebate and incentive program tracking and application status.",
    group: "department",
    tags: ["incentives", "department"],
  },
  {
    slug: "revenue",
    targetHref: "/dashboards/revenue",
    title: "Revenue",
    description: "Revenue by stage, backlog forecasts, location breakdowns, and milestone timelines.",
    group: "executive",
    tags: ["revenue", "executive"],
  },
  {
    slug: "executive-summary",
    targetHref: "/dashboards/executive",
    title: "Executive Summary",
    description: "High-level pipeline and stage analysis with location and monthly trends.",
    group: "executive",
    tags: ["executive", "summary"],
  },
  {
    slug: "locations",
    targetHref: "/dashboards/locations",
    title: "Location Comparison",
    description: "Side-by-side location performance, capacity, and pipeline breakdown.",
    group: "executive",
    tags: ["executive", "locations"],
  },
  {
    slug: "executive-calendar",
    targetHref: "/dashboards/executive-calendar",
    title: "Revenue Calendar",
    description: "Monthly calendar showing daily deal value of scheduled field service work.",
    group: "executive",
    tags: ["executive", "calendar"],
  },
  {
    slug: "service-scheduler",
    targetHref: "/dashboards/service-scheduler",
    title: "Service Schedule",
    description: "Calendar view of Zuper service visit and service revisit jobs.",
    group: "service",
    tags: ["service", "scheduling"],
  },
  {
    slug: "service-backlog",
    targetHref: "/dashboards/service-backlog",
    title: "Service Equipment Backlog",
    description: "Service pipeline equipment forecasting by brand, model, and stage.",
    group: "service",
    tags: ["service", "equipment"],
  },
  {
    slug: "service",
    targetHref: "/dashboards/service",
    title: "Service Pipeline",
    description: "Service deal tracking with stage progression and metrics.",
    group: "service",
    tags: ["service", "pipeline", "additional-pipeline"],
  },
  {
    slug: "sales",
    targetHref: "/dashboards/sales",
    title: "Sales Pipeline",
    description: "Active deals, funnel visualization, and proposal tracking.",
    group: "additional_pipeline",
    tags: ["sales", "pipeline"],
  },
  {
    slug: "dnr",
    targetHref: "/dashboards/dnr",
    title: "D&R Pipeline",
    description: "Detach and reset projects with phase tracking.",
    group: "additional_pipeline",
    tags: ["dnr", "pipeline"],
  },
  {
    slug: "admin-users",
    targetHref: "/admin/users",
    title: "Users",
    description: "Manage user accounts, roles, and access controls.",
    group: "admin_tools",
    tags: ["admin", "access"],
  },
  {
    slug: "admin-activity",
    targetHref: "/admin/activity",
    title: "Activity Log",
    description: "Audit user actions, dashboard views, and system events.",
    group: "admin_tools",
    tags: ["admin", "audit"],
  },
  {
    slug: "admin-security",
    targetHref: "/admin/security",
    title: "Security",
    description: "Review security events, impersonation, and admin activity.",
    group: "admin_tools",
    tags: ["admin", "security"],
  },
  {
    slug: "admin-tickets",
    targetHref: "/admin/tickets",
    title: "Bug Reports",
    description: "View and manage user-submitted bug reports and issues.",
    group: "admin_tools",
    tags: ["admin", "tickets"],
  },
  {
    slug: "qc",
    targetHref: "/dashboards/qc",
    title: "QC Metrics",
    description: "Time-between-stages analytics by office and utility.",
    group: "admin_testing",
    tags: ["admin", "testing", "qc"],
  },
  {
    slug: "project-management",
    targetHref: "/dashboards/project-management",
    title: "Project Management",
    description: "PM workload, DA backlog, stuck deals, and revenue tracking.",
    group: "admin_testing",
    tags: ["admin", "testing", "pm"],
  },
  {
    slug: "design-engineering",
    targetHref: "/dashboards/design-engineering",
    title: "Design & Engineering",
    description: "Cross-state design analytics, status breakdowns, and ops clarification queue.",
    group: "admin_testing",
    tags: ["admin", "testing", "design"],
  },
  {
    slug: "permitting-interconnection",
    targetHref: "/dashboards/permitting-interconnection",
    title: "Permitting & Interconnection",
    description: "Combined P&I analytics, turnaround times, and action-needed views.",
    group: "admin_testing",
    tags: ["admin", "testing", "permitting"],
  },
  {
    slug: "alerts",
    targetHref: "/dashboards/alerts",
    title: "Alerts",
    description: "Overdue installs, PE PTO risks, and capacity overload warnings.",
    group: "admin_testing",
    tags: ["admin", "testing", "alerts"],
  },
  {
    slug: "pe",
    targetHref: "/dashboards/pe",
    title: "PE Dashboard",
    description: "Participate Energy milestone tracking and compliance monitoring.",
    group: "admin_testing",
    tags: ["admin", "testing", "pe"],
  },
  {
    slug: "capacity",
    targetHref: "/dashboards/capacity",
    title: "Capacity Planning",
    description: "Crew capacity vs forecasted installs across all locations.",
    group: "admin_testing",
    tags: ["admin", "testing", "capacity"],
  },
  {
    slug: "pipeline",
    targetHref: "/dashboards/pipeline",
    title: "Pipeline Overview",
    description: "Full project pipeline with filters, priority scoring, and milestone tracking.",
    group: "admin_testing",
    tags: ["admin", "testing", "pipeline"],
  },
  {
    slug: "at-risk",
    targetHref: "/dashboards/at-risk",
    title: "At-Risk Projects",
    description: "Projects with overdue milestones, stalled stages, and severity scoring.",
    group: "admin_testing",
    tags: ["admin", "testing", "risk"],
  },
  {
    slug: "optimizer",
    targetHref: "/dashboards/optimizer",
    title: "Pipeline Optimizer",
    description: "Identify scheduling opportunities and optimize project throughput.",
    group: "admin_testing",
    tags: ["admin", "testing", "optimizer"],
  },
  {
    slug: "zuper-status-comparison",
    targetHref: "/dashboards/zuper-status-comparison",
    title: "Zuper Status Comparison",
    description: "Compare Zuper job statuses and dates with HubSpot deal data.",
    group: "admin_testing",
    tags: ["admin", "testing", "zuper"],
  },
  {
    slug: "zuper-compliance",
    targetHref: "/dashboards/zuper-compliance",
    title: "Zuper Compliance",
    description: "Per-user compliance scorecards for Zuper field service status updates.",
    group: "admin_testing",
    tags: ["admin", "testing", "compliance"],
  },
  {
    slug: "mobile",
    targetHref: "/dashboards/mobile",
    title: "Mobile Dashboard",
    description: "Touch-optimized view for field teams and fast project lookup.",
    group: "admin_testing",
    tags: ["admin", "testing", "mobile"],
  },
  {
    slug: "updates",
    targetHref: "/updates",
    title: "Updates",
    description: "Release notes, changelog, and recent feature updates.",
    group: "documentation",
    tags: ["docs", "changelog"],
  },
  {
    slug: "guide",
    targetHref: "/guide",
    title: "Guide",
    description: "User guide for navigating dashboards and features.",
    group: "documentation",
    tags: ["docs", "guide"],
  },
  {
    slug: "roadmap",
    targetHref: "/roadmap",
    title: "Roadmap",
    description: "Planned features, upcoming work, and development priorities.",
    group: "documentation",
    tags: ["docs", "roadmap"],
  },
  {
    slug: "handbook",
    targetHref: "/handbook",
    title: "Handbook",
    description: "Comprehensive guide to dashboards, features, and workflows.",
    group: "documentation",
    tags: ["docs", "handbook"],
  },
  {
    slug: "sop",
    targetHref: "/sop",
    title: "SOPs",
    description: "Standard operating procedures for operations, scheduling, and workflows.",
    group: "documentation",
    tags: ["docs", "sop"],
  },
  {
    slug: "solar-checkout",
    targetHref: "/prototypes/solar-checkout",
    title: "Solar Checkout Experience",
    description: "Customer-facing solar checkout flow prototype.",
    group: "legacy",
    tags: ["prototype", "legacy"],
  },
  {
    slug: "solar-surveyor",
    targetHref: "/prototypes/solar-surveyor",
    title: "Solar Surveyor v11",
    description: "Next-generation solar site surveyor tool prototype.",
    group: "legacy",
    tags: ["prototype", "legacy"],
  },
];

export function getInternalPrototypeBySlug(slug: string): InternalPagePrototype | undefined {
  return INTERNAL_PAGE_PROTOTYPES.find((item) => item.slug === slug);
}
