-- Interconnection Hub — additive ActivityType enum values.
-- Reuses PermitHubDraft table for drafts (shared across hubs via
-- actionKind prefixing — IC_* won't collide with PERMIT_*).

ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_SUBMITTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_RESUBMITTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_REJECTION_LOGGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_REVISION_ROUTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_REVISION_COMPLETED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_INFO_PROVIDED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_FOLLOWUP';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_APPROVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_HUB_DRAFT_SAVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'IC_HUB_DRAFT_DISCARDED';
