ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DESIGN';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PERMIT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INTERCONNECT';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INTELLIGENCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ROOFING';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MARKETING';
