-- On-Call Electrician Rotations (V1 admin-managed)
-- Spec: docs/superpowers/specs/2026-04-20-on-call-electrician-rotations-design.md
-- Plan: docs/superpowers/plans/2026-04-20-on-call-electrician-rotations.md
--
-- Adds 5 tables + ActivityType enum values for three independent daily rotations
-- (California, Denver, Southern CO). Feature-flagged via ON_CALL_ROTATIONS_ENABLED —
-- tables stay empty until an admin publishes the first schedule.

-- ActivityType enum values
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_POOL_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_POOL_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_POOL_MEMBERS_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_PUBLISHED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_SWAP_REQUESTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_SWAP_ACCEPTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_SWAP_APPROVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_SWAP_DENIED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_SWAP_CANCELLED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_PTO_REQUESTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_PTO_APPROVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_PTO_DENIED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_PTO_CANCELLED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_MANUAL_OVERRIDE';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'ON_CALL_ICAL_TOKEN_ROTATED';

-- OnCallPool: one row per rotation pool. Three expected in v1: California, Denver, Southern CO.
CREATE TABLE IF NOT EXISTS "OnCallPool" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "region" TEXT NOT NULL,
    "shiftStart" TEXT NOT NULL,
    "shiftEnd" TEXT NOT NULL,
    "timezone" TEXT NOT NULL,
    "startDate" TEXT NOT NULL,
    "horizonMonths" INTEGER NOT NULL DEFAULT 3,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastPublishedAt" TIMESTAMP(3),
    "lastPublishedBy" TEXT,
    "lastPublishedThrough" TEXT,
    "icalToken" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnCallPool_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "OnCallPool_name_key" ON "OnCallPool"("name");
CREATE UNIQUE INDEX IF NOT EXISTS "OnCallPool_icalToken_key" ON "OnCallPool"("icalToken");
CREATE INDEX IF NOT EXISTS "OnCallPool_isActive_idx" ON "OnCallPool"("isActive");

-- OnCallPoolMember: rotation order and active-status per CrewMember per pool.
CREATE TABLE IF NOT EXISTS "OnCallPoolMember" (
    "id" TEXT NOT NULL,
    "poolId" TEXT NOT NULL,
    "crewMemberId" TEXT NOT NULL,
    "orderIndex" INTEGER NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "OnCallPoolMember_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "OnCallPoolMember_poolId_crewMemberId_key" ON "OnCallPoolMember"("poolId", "crewMemberId");
CREATE INDEX IF NOT EXISTS "OnCallPoolMember_poolId_orderIndex_idx" ON "OnCallPoolMember"("poolId", "orderIndex");

ALTER TABLE "OnCallPoolMember"
  ADD CONSTRAINT "OnCallPoolMember_poolId_fkey"
  FOREIGN KEY ("poolId") REFERENCES "OnCallPool"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OnCallPoolMember"
  ADD CONSTRAINT "OnCallPoolMember_crewMemberId_fkey"
  FOREIGN KEY ("crewMemberId") REFERENCES "CrewMember"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- OnCallAssignment: single day's on-call shift. Generated by Publish; mutable via Swap/PTO.
-- date is YYYY-MM-DD in pool's local tz, representing SHIFT-START date (5pm -> 7am next day).
CREATE TABLE IF NOT EXISTS "OnCallAssignment" (
    "id" TEXT NOT NULL,
    "poolId" TEXT NOT NULL,
    "date" TEXT NOT NULL,
    "crewMemberId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "originalCrewMemberId" TEXT,
    "sourceRequestId" TEXT,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnCallAssignment_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "OnCallAssignment_poolId_date_key" ON "OnCallAssignment"("poolId", "date");
CREATE INDEX IF NOT EXISTS "OnCallAssignment_crewMemberId_date_idx" ON "OnCallAssignment"("crewMemberId", "date");
CREATE INDEX IF NOT EXISTS "OnCallAssignment_poolId_source_idx" ON "OnCallAssignment"("poolId", "source");

ALTER TABLE "OnCallAssignment"
  ADD CONSTRAINT "OnCallAssignment_poolId_fkey"
  FOREIGN KEY ("poolId") REFERENCES "OnCallPool"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OnCallAssignment"
  ADD CONSTRAINT "OnCallAssignment_crewMemberId_fkey"
  FOREIGN KEY ("crewMemberId") REFERENCES "CrewMember"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "OnCallAssignment"
  ADD CONSTRAINT "OnCallAssignment_originalCrewMemberId_fkey"
  FOREIGN KEY ("originalCrewMemberId") REFERENCES "CrewMember"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- OnCallSwapRequest: two-party swap. Status states: awaiting-counterparty → awaiting-admin → approved/denied/cancelled.
CREATE TABLE IF NOT EXISTS "OnCallSwapRequest" (
    "id" TEXT NOT NULL,
    "poolId" TEXT NOT NULL,
    "requesterCrewMemberId" TEXT NOT NULL,
    "requesterDate" TEXT NOT NULL,
    "counterpartyCrewMemberId" TEXT NOT NULL,
    "counterpartyDate" TEXT NOT NULL,
    "reason" TEXT,
    "status" TEXT NOT NULL,
    "counterpartyAcceptedAt" TIMESTAMP(3),
    "reviewedByUserId" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "denialReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnCallSwapRequest_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "OnCallSwapRequest_poolId_status_idx" ON "OnCallSwapRequest"("poolId", "status");
CREATE INDEX IF NOT EXISTS "OnCallSwapRequest_requesterCrewMemberId_idx" ON "OnCallSwapRequest"("requesterCrewMemberId");
CREATE INDEX IF NOT EXISTS "OnCallSwapRequest_counterpartyCrewMemberId_idx" ON "OnCallSwapRequest"("counterpartyCrewMemberId");

ALTER TABLE "OnCallSwapRequest"
  ADD CONSTRAINT "OnCallSwapRequest_poolId_fkey"
  FOREIGN KEY ("poolId") REFERENCES "OnCallPool"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OnCallSwapRequest"
  ADD CONSTRAINT "OnCallSwapRequest_requesterCrewMemberId_fkey"
  FOREIGN KEY ("requesterCrewMemberId") REFERENCES "CrewMember"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "OnCallSwapRequest"
  ADD CONSTRAINT "OnCallSwapRequest_counterpartyCrewMemberId_fkey"
  FOREIGN KEY ("counterpartyCrewMemberId") REFERENCES "CrewMember"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- OnCallPtoRequest: date-range PTO block. Approval requires reassignments for affected days.
CREATE TABLE IF NOT EXISTS "OnCallPtoRequest" (
    "id" TEXT NOT NULL,
    "poolId" TEXT NOT NULL,
    "crewMemberId" TEXT NOT NULL,
    "startDate" TEXT NOT NULL,
    "endDate" TEXT NOT NULL,
    "reason" TEXT,
    "status" TEXT NOT NULL,
    "reviewedByUserId" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "denialReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OnCallPtoRequest_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "OnCallPtoRequest_poolId_status_idx" ON "OnCallPtoRequest"("poolId", "status");
CREATE INDEX IF NOT EXISTS "OnCallPtoRequest_crewMemberId_idx" ON "OnCallPtoRequest"("crewMemberId");

ALTER TABLE "OnCallPtoRequest"
  ADD CONSTRAINT "OnCallPtoRequest_poolId_fkey"
  FOREIGN KEY ("poolId") REFERENCES "OnCallPool"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "OnCallPtoRequest"
  ADD CONSTRAINT "OnCallPtoRequest_crewMemberId_fkey"
  FOREIGN KEY ("crewMemberId") REFERENCES "CrewMember"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
